'use strict';
/* ============================================================
 * 地图数据：19 张可自由探索的瓦片地图
 * 瓦片：. 草地(遇敌) , 花 ; 深草(遇敌+) P 路 B 桥 S 沙(遇敌)
 *       C 洞窟(遇敌) ^ 山路 = 地板 | 障碍：T树 t树W水 M山 #房
 *       R砖 E服务器 L书架 o桌 X虚空
 * ============================================================ */
(() => {
  const M = G.mapDefs = {};

  /* ============ 福报科技大厦（序章办公室） ============ */
  M.home_office = {
    name: '福报科技大厦17层', pal: 'office', bgm: 'office', battleBg: 'office',
    w: 20, h: 12, spawn: [10, 8], deco: '🥀',
    rows: [
      '====================',
      '=oo=oo=oo==oo=oo=oo=',
      '=oo=oo=oo==oo=oo=oo=',
      '====================',
      '==................==',
      '==..P..........P..==',
      '==..P..........P..==',
      '==..............P..==',
      '==..P..............=',
      '==..P..........P...=',
      '==................==',
      '====================',
    ],
    entities: [
      { x: 10, y: 10, type: 'save', emoji: '🕒', name: '打卡机', id: 'k1' },
      { x: 4, y: 1, type: 'npc', emoji: '👤', name: '工位幽灵', id: 'g1', lines: ['「这个工位……我坐了八年……」', '「键盘上的灰……是我的青春……」'] },
      { x: 15, y: 1, type: 'npc', emoji: '🤵', name: '潘总', id: 'p1', lines: ['「小满？你没死啊！太好了！方案第39版——喂？喂？」', '「信号不好，回头再说！」'] },
      { x: 3, y: 8, type: 'chest', emoji: '📦', id: 'n1', item: 'i_gouqi', n: 2 },
      { x: 17, y: 4, type: 'npc', emoji: '🧹', name: '保洁阿姨', id: 'b1', lines: ['「加班到这么晚啊……阿姨只能帮你把工位擦干净。」', '「孩子，下班吧，天塌不下来。」'] },
    ],
  };

  /* ============ 木鱼村 ============ */
  M.village = {
    name: '木鱼村', pal: 'town', bgm: 'town', battleBg: 'field',
    w: 30, h: 18, spawn: [14, 14], deco: '🌲',
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'T##oooo##..,,..##oooo##,,,..TT',
      'T##oooo##..,,..##oooo##,,,,.TT',
      'T....P.......P.......P.....TTT',
      'T.P..P..W..P..P..,,..P....TTTT',
      'T.P..P..W..P..P..,,..P...TTTTT',
      'T.P..PPPPP..PPPPPPPPPP.......T',
      'T.P....P........P....P.,,....T',
      'T.P....P........P....P.,,....T',
      'T.P....PPPPPPPPPP....P.......,T',
      'T.P......P...........P....,,.T',
      'T.P......P...........PPPPPP..T',
      'T.P......P................P..T',
      'T.P......P...........P...P...T',
      'T.PPPPPPPPP......PPPPP...P...T',
      'T......P..........P......P...T',
      'T......P..........P......P...T',
      'TTTTTTTPPPPPPPPPPPPTTTTTTTTTTT',
    ],
    entities: [
      { x: 14, y: 6, type: 'story', emoji: '👴', name: '村长老木', id: 'elder', main: true, story: 'ch1:start', req: 'ch0_done', done: 'ch1_done',
        altLines: ['「丫头又回来啦？村里功德涨了不少，都是托你的福。」', '「迷雾森林在村西边，路过帮老夫看看那棵老登树还嘴硬不。」'] },
      { x: 20, y: 2, type: 'shop', emoji: '🏪', name: '王婶小卖部', shop: 'village' },
      { x: 3, y: 2, type: 'inn', emoji: '🛏️', name: '木鱼客栈', cost: 30 },
      { x: 8, y: 10, type: 'board', emoji: '📋', name: '委托板' },
      { x: 14, y: 9, type: 'save', emoji: '💠', name: '功德水晶', id: 's1' },
      { x: 24, y: 6, type: 'mini', emoji: '🥁', name: '村口大木鱼', mini: 'muyu' },
      { x: 9, y: 3, type: 'fish', emoji: '🎣', name: '村边池塘' },
      { x: 11, y: 12, type: 'npc', emoji: '🧑', name: '阿伟', id: 'awei', lines: ['「满姐？你不是……在那个世界吗？！」', '「我表弟说他在异世界见过你，我以为是玩笑。」', '「打工是不可能好好打工的，这辈子都不可能。」'] },
      { x: 17, y: 3, type: 'npc', emoji: '🐈', name: '领导', id: 'ld', lines: ['「喵。」', '「喵呜。」（它翻了个身，肚皮朝天：本猫今天不想上班。）'] },
      { x: 6, y: 12, type: 'npc', emoji: '👦', name: '村里小孩', id: 'kid', lines: ['「姐姐你去过迷雾森林吗！里面有大蘑菇！」', '「哥哥说蘑菇会说话！骗人的吧？」'] },
      { x: 22, y: 11, type: 'npc', emoji: '🧙', name: '算命先生', id: 'fortune', lines: ['「我看你印堂……发亮！最近有泼天的富贵！」', '「算错了？不，是命运偷偷改了剧本。」'] },
      { x: 26, y: 14, type: 'npc', emoji: '👵', name: '树下大娘', id: 'granny', lines: ['「当年老木村长也是闯荡过的人哟。」', '「闯荡的结果就是回来敲了四十年木鱼，哈哈哈哈。」'] },
      { x: 4, y: 15, type: 'chest', emoji: '📦', id: 'v1', gold: 50, item: 'i_bandaid', n: 2 },
      { x: 27, y: 3, type: 'chest', emoji: '📦', id: 'v2', item: 'i_cola', n: 2 },
      { x: 19, y: 15, type: 'chest', emoji: '📦', id: 'v3', item: 'i_huoxiang', n: 2, gold: 30 },
      { x: 7, y: 17, type: 'exit', to: 'farm', toX: 12, toY: 2 },
      { x: 1, y: 9, type: 'exit', to: 'forest', toX: 27, toY: 10 },
    ],
  };

  /* ============ 村外农田（farm） ============ */
  M.farm = {
    name: '村外农田', pal: 'grass', bgm: 'field', battleBg: 'farm',
    encounters: ['boar_mini', 'slime_green', 'monkey_malou'],
    w: 26, h: 16, spawn: [12, 2], deco: '🌲',
    rows: [
      'TTTTTTTTTTTTTTTPPTTTTTTTTT',
      'T..........,...P.,.......T',
      'T..,,,,.....,.P...,,.....T',
      'T..,,,,,,....P....,,,....T',
      'T....,...;;;P;......,....T',
      'T..P.......;P;...........T',
      'T..P......;;P;;....,.....T',
      'T..P.......P.....;;;;....T',
      'T..PPPPPPPPP......,......T',
      'T..........P......,......T',
      'T..,,,,....P...,,,,,,....T',
      'T..,W W....P...,,,,,,....T',
      'T...WWW....P.............T',
      'T..........P.......R.....T',
      'T..........P.............T',
      'TTTTTTTTTTTPPTTTTTTTTTTTTT',
    ],
    entities: [
      { x: 12, y: 1, type: 'exit', to: 'village', toX: 7, toY: 16 },
      { x: 16, y: 0, type: 'exit', to: 'thursday', toX: 2, toY: 7 },
      { x: 6, y: 5, type: 'npc', emoji: '🛖', name: '稻草人', id: 'sc', lines: ['「（稻草人的斗笠上贴着一张纸条：本田已投保，野猪慎拱。）」'] },
      { x: 20, y: 8, type: 'npc', emoji: '🐖', name: '野猪仔', id: 'b1', lines: ['「哼哼……」（它眼神心虚，大概是野猪王的孩子。）', '「哼！哼哼！」（翻译：爸爸输给了人类，但我们不认输！）'] },
      { x: 22, y: 4, type: 'monster', emoji: '🦙', name: '神兽·驼驼', id: 'tt1', enemies: ['alpaca_tuotuo'],
        lines: '（传说中的神兽驼驼！据说抓住它能获得海量经验！它吐了你一口口水，然后准备跑路！）' },
      { x: 3, y: 10, type: 'chest', emoji: '📦', id: 'f1', item: 'i_latang', n: 2 },
      { x: 23, y: 13, type: 'chest', emoji: '📦', id: 'f2', gold: 80, item: 'i_bandaid', n: 2 },
    ],
  };

  /* ============ 迷雾森林·外圈（forest） ============ */
  M.forest = {
    name: '迷雾森林·外圈', pal: 'forest', bgm: 'forest', battleBg: 'forest',
    encounters: ['wolf_mist', 'mushroom', 'bee_juan', 'slime_gray'],
    w: 30, h: 20, spawn: [27, 10], deco: '🌲',
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
      'TT..;;..TT....;;...TT...;;..TT',
      'T..;;;;....TT.;;,..TT..;;...TT',
      'T..;;..TTT....;;.....;;..;;.TT',
      'T.....TTTTT.......TTT....;;.TT',
      'TT..P.TTTTTTT..;;.TTTTT....,.T',
      'T...P.......T..;;......;;....T',
      'T.P.P.......PPPP..TTT..;;....T',
      'T.P.P..;;;..T..P..TTT.......TT',
      'T.P.PP.;;;..T..P......;;;..TTT',
      'T..P....,...T..PPPPP.;;;...TTT',
      'T..PPPPPPPP.........P....;..TT',
      'T.....;;...T....;;...P.......T',
      'TT..;;;;;..T..;;;;;..P..;;...T',
      'T..........T..;;;;;..PP......T',
      'T.PPPPPPPPPP.......T..P....TTT',
      'T.P........TTTT....T..P...TTTT',
      'T.P...;;;.......;;;...P.......',
      'T.P..........T.......P....TTTT',
      'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    entities: [
      { x: 29, y: 17, type: 'exit', to: 'village', toX: 1, toY: 9 },
      { x: 5, y: 5, type: 'exit', to: 'forest2', toX: 12, toY: 16 },
      { x: 1, y: 9, type: 'exit', to: 'corrupted', toX: 21, toY: 8 },
      { x: 5, y: 4, type: 'story', emoji: '🗿', name: '森林界碑', id: 'gate', main: true, story: 'ch2:start', req: 'ch1_done', done: 'ch2_done',
        altLines: ['「界碑上刻着：迷雾森林，谣言之雾，蘑菇之乡。」', '「界碑背面有小字：蘑菇并不都很友好。」'] },
      { x: 24, y: 3, type: 'npc', emoji: '👵', name: '采药婆婆', id: 'herb', lines: ['「采药要看叶子背面，写着的才是真话。」', '「这林子里的话，一半是雾说的。」'] },
      { x: 20, y: 6, type: 'story', emoji: '🕳️', name: '隐者洞窟', id: 'hermit', story: 'side:q_hermit', req: 'ch2_done', done: 'q_hermit_done',
        altLines: ['「洞里传来均匀的呼吸声，好像有人在修炼，也好像只是在睡觉。」'] },
      { x: 27, y: 12, type: 'monster', emoji: '🦙', name: '神兽·驼驼', id: 'tt2', enemies: ['alpaca_tuotuo'],
        lines: '（树影里探出一颗毛茸茸的脑袋——是驼驼！它对着你吐了口口水，转身就跑！）' },
      { x: 14, y: 10, type: 'chest', emoji: '📦', id: 'fo1', item: 'i_fengyoujing', n: 2 },
      { x: 8, y: 18, type: 'chest', emoji: '📦', id: 'fo2', gold: 120 },
      { x: 26, y: 1, type: 'chest', emoji: '📦', id: 'fo3', item: 'i_catvideo', n: 1 },
    ],
  };

  /* ============ 迷雾森林·深处（forest2） ============ */
  M.forest2 = {
    name: '迷雾森林·深处', pal: 'forest', bgm: 'forest', battleBg: 'forest',
    encounters: ['wolf_mist', 'mushroom', 'slime_gray'],
    w: 26, h: 18, spawn: [12, 16], deco: '🌲',
    rows: [
      'TTTTTTTTTTTTTTTPPTTTTTTTTT',
      'TT..;;...;;..TTP..;;...;TT',
      'T..;;;;.;;;;..P..;;;;.;;;T',
      'T..;;...;;....P....;;...;T',
      'T.....;;...TTTP;;;.......T',
      'T..;;;....T;;TPP;;;....,TT',
      'T..;;;..TTT;;.....;;...,,T',
      'T....;..TTT....;;;....,,,T',
      'T..PPPPPPPPPP......;;..,.T',
      'T..P......T.P...;;......,T',
      'T..P..;;..T.P..TTT.......T',
      'T..PPPPPPPT.P..TTTPPPP...T',
      'T.....;;.T.P........P....T',
      'T..;;;...T.PPPPPPPPPP....T',
      'T..;;;...T.........T.....T',
      'T.......TT....;;;..T.....T',
      'T........P....;;;..T.....T',
      'TTTTTTTTTPPTTTTTTTTTTTTTTT',
    ],
    entities: [
      { x: 12, y: 17, type: 'exit', to: 'forest', toX: 5, toY: 6 },
      { x: 16, y: 0, type: 'exit', to: 'library', toX: 2, toY: 8 },
      { x: 5, y: 8, type: 'heal', emoji: '⛲', name: '精灵泉', lines: '💧 精灵泉闪着银光。全队泡了泡，完全恢复！（菇勇者：喝之前许愿，效果更佳。）' },
      { x: 20, y: 7, type: 'npc', emoji: '🍄', name: '蘑菇精灵', id: 'mg', lines: ['「菌菌子！人类！欢迎来到蘑菇圈！」', '「记住哦：越好看的蘑菇越有脾气！」'] },
      { x: 8, y: 13, type: 'npc', emoji: '🟢', name: '路过的史莱姆', id: 'sl2', req: 'ch2_done', lines: ['「听说有几只史莱姆跟着人类讨伐魔王去了？！」', '「吨吨前辈……是我们的偶像！」'] },
      { x: 22, y: 15, type: 'chest', emoji: '📦', id: 'f21', item: 'i_lanyao', n: 2 },
      { x: 3, y: 2, type: 'chest', emoji: '📦', id: 'f22', gold: 150, item: 'i_dayao', n: 1 },
    ],
  };

  /* ============ 上古图书馆（library） ============ */
  M.library = {
    name: '上古图书馆', pal: 'cave', bgm: 'dungeon', battleBg: 'dungeon',
    encounters: ['ghost_meeting', 'mushroom', 'parrot_gangjing'],
    w: 22, h: 16, spawn: [2, 8], deco: '🥀',
    rows: [
      '======================',
      '=LLLL==LLLL==LLLL==LL=',
      '=LLLL==LLLL==LLLL==LL=',
      '=--------------------=',
      '=--o=o----------o=o--=',
      '=---------------------',
      '=--o=o----oo----o=o--=',
      '=---------oo----------',
      '----------------------',
      '=--o=o----------o=o--=',
      '=---------------------',
      '=LLLL==LLLL==LLLL==LL=',
      '=LLLL==LLLL==LLLL==LL=',
      '=---------------------',
      '=---------------------',
      '======================',
    ],
    entities: [
      { x: 1, y: 8, type: 'exit', to: 'forest2', toX: 16, toY: 1 },
      { x: 11, y: 3, type: 'story', emoji: '🗿', name: '门卫魔像', id: 'guard', main: true, story: 'ch2:library_outside', req: 'ch1_done', done: 'ch2_done',
        altLines: ['「『梗力准入考试』已由你们通过。终身有效。」', '「温馨提示：B4层机房重地，闲人免进。特殊访客除外。」'] },
      { x: 18, y: 12, type: 'story', emoji: '📕', name: 'B4层机房', id: 'b4', story: 'side:q_qianji', req: 'ch6_done', done: 'q_qianji_done',
        altLines: ['「机房的大门紧锁。门缝里透出一点微弱的动力灯。」'] },
      { x: 5, y: 6, type: 'npc', emoji: '👻', name: '馆员幽灵', id: 'lib', lines: ['「嘘——有人在看书。」', '「他看了三百年同一页，别打扰他，快看完了。」'] },
      { x: 14, y: 9, type: 'npc', emoji: '🐛', name: '书虫', id: 'worm', lines: ['「我吃掉了《魔王饲养手册》第三章，味道像过期辣条。」'] },
      { x: 4, y: 14, type: 'chest', emoji: '📦', id: 'l1', item: 'i_mola', n: 2 },
      { x: 19, y: 4, type: 'chest', emoji: '📦', id: 'l2', gold: 200, item: 'i_lanyao', n: 2 },
    ],
  };

  /* ============ 王都·咕咚城（capital） ============ */
  M.capital = {
    name: '王都·咕咚城', pal: 'town', bgm: 'town', battleBg: 'field',
    w: 48, h: 20, spawn: [16, 17], deco: '🌲',
    rows: [
      'TTTTTT##oooooooooo##TTTT##oooooooo##TTTTTTTTTTTT',
      'TTTTTT#oooooooooooo#TTTT#oooooooooo#TTTTTTTTTTTT',
      'TTTTTT#oooooooooooo#TTTT#oooooooooo#TTTTTTTTTTTT',
      'TTTTTTT...P.......P.T......P.......P.TTTTTTTTTTT',
      'TT........PPPPPPPPPPPPPPPPPPPP.......TTTTTTTTTT',
      'T..,,.....................P......,,,....TTTTTTTT',
      'T..,,...##.........,......P.....,,,,,...TTTTTTTT',
      'T.......,##....P....,.....P......,,,....TTTTTTTT',
      'T..W....,.....PP..........PPPP.......P..TTTTTTTT',
      'T..WWW..,.....P....................P..P..TTTTTTT',
      'T..WWW..,.....PPPPPPPPPPPPPPPPPPPPP..P.......TTT',
      'T..W....,..................P.........P....,..TTT',
      'T.......,.....,,,,,........P....,,,,,P....,..TTT',
      'T..,,...,.....,,,,,....,,,,,....,,,,,P....,..TTT',
      'T..,,...PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP....,..TT',
      'T..................P.................,......TTTT',
      'T...,......,,,......P.........,,,...........TTTT',
      'T..................PP...................,,,..TTT',
      'T.....,,,.....................,,,.....,,,,,..TTT',
      'TTTTTTTTTTTTTTTTTTTPPTTTTTTTTTTTTTTTTTTTTTTTTTTT',
    ],
    entities: [
      { x: 19, y: 19, type: 'exit', to: 'factory', toX: 11, toY: 2 },
      { x: 8, y: 0, type: 'exit', to: 'canal', toX: 17, toY: 6 },
      { x: 25, y: 0, type: 'exit', to: 'snow_mountain', toX: 12, toY: 14 },
      { x: 26, y: 2, type: 'story', emoji: '💁', name: '公会前台·阿珍', id: 'azz', main: true, story: 'ch3:start', req: 'ch2_done', done: 'ch3_done',
        altLines: ['「A级新人回来啦！公会茶水间永远为你开放。」', '「委托板更新了悬赏，小心键盘侠，他们最近话很多。」'] },
      { x: 6, y: 7, type: 'shop', emoji: '🏬', name: '王都百货', shop: 'capital' },
      { x: 11, y: 1, type: 'inn', emoji: '🍺', name: '碎梦酒馆', cost: 80 },
      { x: 13, y: 2, type: 'mini', emoji: '✊', name: '猜拳摊', mini: 'rps' },
      { x: 28, y: 1, type: 'mini', emoji: '🎰', name: '王都扭蛋机', mini: 'gacha' },
      { x: 16, y: 10, type: 'board', emoji: '📋', name: '公会委托板' },
      { x: 16, y: 15, type: 'save', emoji: '💠', name: '王都存档水晶', id: 's2' },
      { x: 4, y: 12, type: 'npc', emoji: '🧑', name: '排队的市民', id: 'q1', lines: ['「这家的网红面包要排三个小时。」', '「值得吗？……不知道，但大家都在排。」'] },
      { x: 30, y: 8, type: 'npc', emoji: '💂', name: '卫兵阿强', id: 'aq', lines: ['「阿珍今天也……咳，没什么。巡逻！巡逻！」', '「最近运河那边有个不说话的骑士，怪吓人的。」'] },
      { x: 12, y: 13, type: 'npc', emoji: '👩', name: '灰衣妇人', id: 'grey', lines: ['「今天的面包……和昨天一个味道……」', '「（她接过了你递去的快乐水，眼睛亮了一下。）谢谢……」'] },
      { x: 22, y: 12, type: 'npc', emoji: '🤳', name: '街头主播', id: 'streamer', lines: ['「家人们！今天带大家逛王都！刷个火箭！」', '「啊这位冒险者！给个采访！你对班味怎么看？」'] },
      { x: 32, y: 16, type: 'npc', emoji: '👸', name: '兜帽舞者', id: 'lele', req: 'ch3_done', lines: ['「公务在身也要跳舞！这是原则问题！」', '「下届夏日祭，本小姐给你留C位！」'] },
      { x: 2, y: 17, type: 'chest', emoji: '📦', id: 'c1', item: 'i_naicha', n: 1 },
      { x: 33, y: 4, type: 'chest', emoji: '📦', id: 'c2', gold: 160 },
      { x: 20, y: 5, type: 'chest', emoji: '📦', id: 'c3', item: 'i_v50', n: 1 },
    ],
  };

  /* ============ 王都工坊区（factory） ============ */
  M.factory = {
    name: '王都工坊区', pal: 'office', bgm: 'office', battleBg: 'office',
    encounters: ['bee_juan', 'keyboard_warrior', 'bat_996'],
    w: 24, h: 16, spawn: [11, 2], deco: '🥀',
    rows: [
      '########################',
      '#....P........P........#',
      '#....P........P........#',
      '#PPPPPPPPPPPPPPPPPPPP..#',
      '#....P........P.....R..#',
      '#.EE.P...;;...P..;;....#',
      '#.EE.P...;;...P..;;....#',
      '#....P........P........#',
      '#PPPPPPPPPPPPPPPPPPPP..#',
      '#....P........P........#',
      '#.EE.P...;;...P...;;...#',
      '#....P........P........#',
      '#....P...;;...P........#',
      '#....P........P.....R..#',
      '#....P........P........#',
      '########################',
    ],
    entities: [
      { x: 11, y: 1, type: 'exit', to: 'capital', toX: 19, toY: 18 },
      { x: 4, y: 10, type: 'npc', emoji: '👨‍🔧', name: '铁匠', id: 'smith', req: 'ch3_done', lines: ['「我给女儿买了蛋糕！最大的那种！」', '「以后打铁只打半天！下午陪家人！」', '「（他一边说一边忍不住敲了两下铁，骄傲地挺起胸。）」'] },
      { x: 17, y: 5, type: 'npc', emoji: '👷', name: '工人', id: 'w1', lines: ['「自从灰雾散了，下班居然有天光。」', '「原来太阳落山是这个颜色的。」'] },
      { x: 6, y: 13, type: 'chest', emoji: '📦', id: 'fa1', item: 'i_gouqi', n: 2 },
      { x: 20, y: 13, type: 'chest', emoji: '📦', id: 'fa2', gold: 130, item: 'i_cola', n: 1 },
    ],
  };

  /* ============ 黑金镇（mine_town） ============ */
  M.mine_town = {
    name: '黑金镇', pal: 'town', bgm: 'town', battleBg: 'field',
    encounters: ['monkey_malou', 'catfish_moyu'],
    w: 26, h: 16, spawn: [12, 14], deco: '🌲',
    rows: [
      'TTTTTTTTT##oooooo##TTTTTTT',
      'TTTTTTTTT#oooooooo#TTTTTTT',
      'TTTTTTTTT#oooooooo#TTTTTTT',
      'TTT,,.......P......,....TT',
      'TT,,,...;;;.P....,,,,...TT',
      'TT,,....;;.PP...,,,,,,..TT',
      'TT.......;.P....,,,,,,..TT',
      'TT..W....;.P.........,..TT',
      'TT..WW...;.PPPPPPPP.....TT',
      'TT..WW...;......P.,,....TT',
      'TT.......;.;;;;.P.,,....TT',
      'TT..,,,..;......P.......TT',
      'TT..,,,..;.;;;;.P..R....TT',
      'TT.......;......P.......TT',
      'TT.......PPPPPPPP.......TT',
      'TTTTTTTTTTPPTTTTTTTTTTTTTT',
    ],
    entities: [
      { x: 11, y: 15, type: 'exit', to: 'capital', toX: 20, toY: 18 },
      { x: 12, y: 0, type: 'exit', to: 'mine', toX: 13, toY: 18 },
      { x: 13, y: 1, type: 'story', emoji: '🫓', name: '宣讲台', id: 'bing', main: true, story: 'ch4:start', req: 'ch3_done', done: 'ch4_done',
        altLines: ['「宣讲台空了。地上还留着一张没发完的饼味传单。」', '「矿工们说：布姐走的时候，好像松了口气。」'] },
      { x: 18, y: 2, type: 'shop', emoji: '⚒️', name: '铁匠铺', shop: 'mine' },
      { x: 4, y: 2, type: 'inn', emoji: '🛏️', name: '矿工旅店', cost: 60 },
      { x: 8, y: 11, type: 'story', emoji: '🎪', name: '龙王考场', id: 'exam', story: 'side:q_dundun', req: 'ch4_done', done: 'q_dundun_done',
        altLines: ['「考场已结业。门口贴着吨吨的证书复印件，旁边写着：本镇首位龙王（见习）。」'] },
      { x: 17, y: 10, type: 'board', emoji: '📋', name: '镇口委托板' },
      { x: 12, y: 9, type: 'save', emoji: '💠', name: '镇中心水晶', id: 's3' },
      { x: 5, y: 7, type: 'npc', emoji: '👷', name: '矿工老张', id: 'kz', lines: ['「布姐再来讲课我也不信了！饼不能当饭吃！」', '「……不过她教的那套PPT，我拿去跟爆老板谈涨薪，还真成了！」'] },
      { x: 21, y: 7, type: 'npc', emoji: '🧔', name: '退休矿工', id: 'ret', lines: ['「挖了一辈子矿，悟了个理：日子是自己的，矿是老板的。」'] },
      { x: 22, y: 12, type: 'npc', emoji: '🐑', name: '镇上的羊', id: 'sheep', lines: ['「咩。」', '「（它眼神空洞，似乎也被上过班。）」'] },
      { x: 3, y: 13, type: 'chest', emoji: '📦', id: 'mt1', item: 'i_dayao', n: 1 },
      { x: 23, y: 4, type: 'chest', emoji: '📦', id: 'mt2', gold: 110 },
    ],
  };

  /* ============ 废弃矿坑（mine） ============ */
  M.mine = {
    name: '废弃矿坑', pal: 'cave', bgm: 'dungeon', battleBg: 'dungeon',
    encounters: ['resume_golem', 'kpi_inspector', 'bat_996', 'punch_clock'],
    w: 28, h: 20, spawn: [13, 18], deco: '🥀',
    rows: [
      'MMMMMMMMMMMMMMMMMMMMMMMMMMMM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCCM',
      'MCCRRCCCCCCCCCRRCCCCCCCCRRCM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCCM',
      'MCRRCCCCMMCCCCCCCMMCCCCCCCCM',
      'MCCCCCCCCMMCCCCCMMCCCRRCCCCM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCCM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCCM',
      'MCCMMCCCCCCCCRRCCCCCCCMMCCCCM',
      'MCCMMCCCCCCCCCCCCCCCC MMCCCCM',
      'MCCCCCCCCCC MMCCCCCCCCCCCCCM',
      'MCCRRC MMCCCCCC MMCCCCCCCCCM',
      'MCCCCCC MMMCCCCCCCCCCRRCCCCM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCCM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCCM',
      'MCRRCCCCCCCCCCCCCCCCCCCCCECM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCEM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCCM',
      'MCCCCCCCCCCCCCCCCCCCCCCCCCCM',
      'MMMMMMMMMMMMMMCCMMMMMMMMMMMM',
    ],
    entities: [
      { x: 13, y: 19, type: 'exit', to: 'mine_town', toX: 12, toY: 1 },
      { x: 7, y: 10, type: 'npc', emoji: '🧑', name: '迷路矿工', id: 'lost', lines: ['「我在里面转了三天……出口在哪？」', '「什么？门口？我进去的时候它明明在左边……」'] },
      { x: 24, y: 15, type: 'npc', emoji: '👁️', name: '深渊残响', id: 'aby', req: 'ch4_done', lines: ['「（岩壁上残留着巨眼的影子，声音微弱得像叹息。）」', '「……有人往深渊里，投了一束光。」'] },
      { x: 3, y: 2, type: 'chest', emoji: '📦', id: 'm1', item: 'i_mola', n: 2, gold: 100 },
      { x: 25, y: 2, type: 'chest', emoji: '📦', id: 'm2', item: 'i_v50', n: 1 },
      { x: 3, y: 17, type: 'chest', emoji: '📦', id: 'm3', gold: 260 },
      { x: 25, y: 6, type: 'chest', emoji: '📦', id: 'm4', item: 'i_dayao', n: 2 },
    ],
  };

  /* ============ 椰风湾（beach） ============ */
  M.beach = {
    name: '椰风湾', pal: 'sand', bgm: 'sky', battleBg: 'beach',
    encounters: ['catfish_moyu', 'icecream_assassin', 'turtle_noreply', 'pigeon_gugu'],
    w: 30, h: 18, spawn: [15, 3], deco: '🌴',
    rows: [
      'tttttttttttttPPtttttttttttttt',
      'tt..........,P,...........ttt',
      'tt..;;......,P,....;;.....ttt',
      'tt..;;;.....,P,.....;;....ttt',
      'tt...;;.....,P,......;;...ttt',
      'tt....,,....,P,.......;...ttt',
      'ttSSSSSSSSSSSPSSSSSSSSSSS..tt',
      'tSSSSSSSSSSSSPSSSSSSSSSSS..tt',
      'tSSS..SSSSSSSPSSSS..SSSSS..tt',
      'tSSS....SSSSPSSSSS...SSS...tt',
      'tSSSSS...SSSPSS....W..S....tt',
      'tSSSSSSS..SSPS..WWWWW..S...tt',
      'tSSS WWWWW.WPS WWWWWWW.....tt',
      'tSS WWWWWWWWW S WWWWW......tt',
      'tSS WWWWWWWWWWW WWWWW...;;.tt',
      'tSS..WWWWWWWWWWW.WW.....;;.tt',
      'tSSS...WWWWWWWWW........;;.tt',
      'ttSSSSSSWWWWWWWWSSSSSSSSS..tt',
    ],
    entities: [
      { x: 14, y: 0, type: 'exit', to: 'capital', toX: 22, toY: 18 },
      { x: 15, y: 4, type: 'story', emoji: '👸', name: '祭坛舞台', id: 'stage', main: true, story: 'ch5:start', req: 'ch4_done', done: 'ch5_done',
        altLines: ['「祭坛上留着科目三的舞台印子。渔民们路过都会扭两下。」'] },
      { x: 20, y: 6, type: 'chest', emoji: '🍉', name: '华哥的瓜摊', id: 'melon', item: 'i_cola', n: 2, gold: 20 },
      { x: 8, y: 9, type: 'fish', emoji: '🎣', name: '近海钓点' },
      { x: 26, y: 12, type: 'fish', emoji: '🎣', name: '礁石钓点' },
      { x: 4, y: 6, type: 'heal', emoji: '♨️', name: '山腰温泉', lines: '♨️ 温泉冒着热气，卡皮巴拉在旁边点了点头。全队完全恢复！' },
      { x: 24, y: 8, type: 'mini', emoji: '✊', name: '沙滩猜拳摊', mini: 'rps' },
      { x: 5, y: 12, type: 'story', emoji: '🎣', name: '钓鱼佬老钓', id: 'oldfish', story: 'side:q_fishing', req: 'ch5_done', done: 'q_fishing_done',
        altLines: ['「冠军就是你！今年我把奖杯刻上你的名字，明年你等着被超越！」'] },
      { x: 18, y: 13, type: 'npc', emoji: '🦀', name: '蟹老板', id: 'crab', req: 'ch5_done', lines: ['「秘方想起来了！其实就是多放蟹黄！」', '「……好像是句废话。但我说出来那一刻特别踏实！」'] },
      { x: 27, y: 3, type: 'npc', emoji: '🍉', name: '华哥', id: 'hua', lines: ['「瓜保熟！话保真！人保暖！」', '「下回来，教你两手切瓜刀法，大陆前十那种。」'] },
      { x: 10, y: 15, type: 'chest', emoji: '📦', id: 'b1', item: 'i_fengyoujing', n: 2 },
      { x: 3, y: 3, type: 'chest', emoji: '📦', id: 'b2', gold: 140, item: 'i_cola', n: 1 },
      { x: 28, y: 16, type: 'chest', emoji: '📦', id: 'b3', item: 'i_naicha', n: 1 },
    ],
  };

  /* ============ 王都运河（canal） ============ */
  M.canal = {
    name: '王都运河', pal: 'grass', bgm: 'field', battleBg: 'field',
    encounters: ['turtle_noreply', 'keyboard_warrior'],
    w: 20, h: 12, spawn: [17, 6], deco: '🌲',
    rows: [
      'WWWWWWWWWWTTTTTTTTTT',
      'WWWWWWWWWWT......,TT',
      'WWWWWWWWWWT.;;..,.TT',
      'WWWWWWWWWWP......TTT',
      'WWWWWWWWWWP;;...T.TT',
      'WWWWWWWWWWP.......TT',
      'WWWWWWWWWWP..;;;..TT',
      'WWWWWWWWWPPPPPPPPPTT',
      'WWWWWWWWWWTT..P...TT',
      'WWWWWWWWWWTT..P...TT',
      'WWWWWWWWWWTT..P...TT',
      'WWWWWWWWWWTTTPPTTTTT',
    ],
    entities: [
      { x: 18, y: 6, type: 'exit', to: 'capital', toX: 9, toY: 1 },
      { x: 11, y: 7, type: 'exit', to: 'road_truck', toX: 19, toY: 6 },
      { x: 12, y: 5, type: 'npc', emoji: '🛡️', name: '放哨的骑士', id: 'kn', req: 'ch6_done', lines: ['「……」（他看见你，微微点头，然后继续望向河面。）', '「（他桌上放着一本《如何回复消息》，翻到第三页。）」'] },
      { x: 12, y: 1, type: 'fish', emoji: '🎣', name: '运河钓点' },
      { x: 14, y: 10, type: 'chest', emoji: '📦', id: 'cn1', item: 'i_huoxiang', n: 2 },
      { x: 15, y: 1, type: 'chest', emoji: '📦', id: 'cn2', gold: 90 },
    ],
  };

  /* ============ 初代勇者的故乡遗迹（memory） ============ */
  M.memory = {
    name: '初代勇者的故乡遗迹', pal: 'memory', bgm: 'sad', battleBg: 'dungeon',
    encounters: ['ghost_meeting', 'resume_golem'],
    w: 22, h: 14, spawn: [19, 7], deco: '🥀',
    rows: [
      'tttttttttttttttttttttt',
      'tt..;;....##....;;..tt',
      'tt..;;....##....;;..tt',
      't.........P.........tt',
      't....;;...P....;;....tt',
      't.........P.........tt',
      't...R....PPPP....R...tt',
      't.........P.........tt',
      't...;;...PPPP...;;...tt',
      't.........P.........tt',
      't..,,....PPPP....,,.tt',
      't.........P........tt',
      'tt........P.......ttt',
      'tttttttttttttttttttttt',
    ],
    entities: [
      { x: 20, y: 7, type: 'exit', to: 'capital', toX: 10, toY: 1 },
      { x: 10, y: 6, type: 'story', emoji: '🪦', name: '描新的石碑', id: 'stone', main: true, story: 'ch6:start', req: 'ch5_done', done: 'ch6_done',
        altLines: ['「石碑很干净，像昨天才被人擦过。」', '「最新的那一块上，多了一行小字：『他下班了。』」'] },
      { x: 11, y: 2, type: 'npc', emoji: '🗿', name: '墨守', id: 'ms', req: 'ch6_done', lines: ['「……现在我不是卫兵了。我是看门的。给人看门，挺好。」', '「有空常来。他……也在的。」'] },
      { x: 4, y: 12, type: 'chest', emoji: '📦', id: 'mm1', item: 'i_catvideo', n: 2 },
      { x: 17, y: 12, type: 'chest', emoji: '📦', id: 'mm2', gold: 180, item: 'i_naicha', n: 1 },
    ],
  };

  /* ============ 被污染的林地（corrupted） ============ */
  M.corrupted = {
    name: '被污染的林地', pal: 'forest', bgm: 'dungeon', battleBg: 'forest',
    encounters: ['slime_gray', 'ghost_meeting', 'ppt_drone'],
    w: 24, h: 16, spawn: [21, 8], deco: '🥀',
    rows: [
      'tttttttttttttttttttttttt',
      'tt;;..tt....;;...tt..;tt',
      't..;;....;;;....;;....;t',
      't.;..tt.......;;...;;..t',
      't....tt..;;;........;;.t',
      't.;;....;;....tt...;;..t',
      't..;;.....;;..tt..;;...t',
      't....;;;......;;....;;.t',
      't.;;....;;;;;;;....;;..t',
      't..;;..;;.....;;..;;...t',
      't...;;......;;....;;...t',
      't..;;...;;....;;.;;....t',
      't......;;...;;.....;;..t',
      't.;;.....;;;....;;....tt',
      't...;;.......;;.....;.tt',
      'tttttttttttttttttttttttt',
    ],
    entities: [
      { x: 22, y: 8, type: 'exit', to: 'forest', toX: 2, toY: 9 },
      { x: 4, y: 8, type: 'npc', emoji: '🥀', name: '回声雾', id: 'echo', lines: ['「「你们来啦。」」', '「（它学你说话，但语气软了很多，像在道歉。）」'] },
      { x: 2, y: 1, type: 'chest', emoji: '📦', id: 'cr1', item: 'i_mola', n: 2, gold: 150 },
      { x: 21, y: 14, type: 'chest', emoji: '📦', id: 'cr2', item: 'i_v50', n: 1 },
      { x: 12, y: 4, type: 'chest', emoji: '📦', id: 'cr3', gold: 220 },
    ],
  };

  /* ============ 天上界·云端机房（sky） ============ */
  M.sky = {
    name: '天上界·云端机房', pal: 'sky', bgm: 'sky', battleBg: 'heaven',
    encounters: ['cloud_ling', 'server_rack', 'firewall_imp'],
    w: 30, h: 18, spawn: [14, 15], deco: '☁️',
    rows: [
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
      'XX....EE....EE......EE....E.XX',
      'XX..,.EE....EE..,,..EE....E.XX',
      'XX....,......................XX',
      'XXEE....EEEE....EE....EE....XX',
      'XXEE....EEEE....EE....EE....XX',
      'XX..........................XX',
      'XX..EE......,,....EE......E.XX',
      'XX..EE......,,....EE......E.XX',
      'XX..........................XX',
      'XX.....EE....EE....EE.......XX',
      'XX..,..EE....EE....EE...,...XX',
      'XX..........................XX',
      'XXEE.....EE......EE.....EE..XX',
      'XXEE.....EE......EE.....EE..XX',
      'XX..........................XX',
      'XX............,,.............XX',
      'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    ],
    entities: [
      { x: 14, y: 15, type: 'story', emoji: '🌸', name: '靠枕堆神殿', id: 'vivian', main: true, story: 'ch7:start', req: 'ch6_done', done: 'ch7_done',
        altLines: ['「薇薇安正趴在靠枕堆上补觉，脚边立着牌子：『认真工作中（梦里）』。」'] },
      { x: 24, y: 15, type: 'shop', emoji: '☁️', name: '功德商店', shop: 'sky' },
      { x: 5, y: 15, type: 'mini', emoji: '🎰', name: '天界扭蛋机', mini: 'gacha' },
      { x: 8, y: 2, type: 'heal', emoji: '🐹', name: '稳定君的云', lines: '🐹 稳定君慢吞吞地拍了拍云朵。云变成温热的泉水，全队完全恢复。它的表情全程没变过。' },
      { x: 20, y: 6, type: 'story', emoji: '📄', name: '报表山', id: 'chips', story: 'side:q_chips', req: 'ch7_done', done: 'q_chips_done',
        altLines: ['「报表山已被清理干净。原地上摆着一袋吃空了的薯片袋，被供成了小神龛。」'] },
      { x: 2, y: 3, type: 'npc', emoji: '☁️', name: '一朵云', id: 'cloud1', lines: ['（它变成兔子的样子，又变回去。似乎在说：都行。）'] },
      { x: 27, y: 8, type: 'npc', emoji: '👼', name: '实习天使', id: 'angel', lines: ['「自从女神认真工作，我天天加班……不对，这句话好耳熟。」'] },
      { x: 4, y: 13, type: 'chest', emoji: '📦', id: 'sk1', item: 'i_ningmeng', n: 2 },
      { x: 27, y: 1, type: 'chest', emoji: '📦', id: 'sk2', gold: 300 },
      { x: 14, y: 9, type: 'chest', emoji: '📦', id: 'sk3', item: 'i_yumao', n: 1 },
    ],
  };

  /* ============ 魔王城·加班大厦（castle） ============ */
  M.castle = {
    name: '加班大厦', pal: 'office', bgm: 'office', battleBg: 'office',
    encounters: ['bat_996', 'resume_golem', 'kpi_inspector', 'punch_clock', 'ppt_drone'],
    w: 26, h: 22, spawn: [12, 19], deco: '🥀',
    rows: [
      '##########################',
      '#.....EE......EE.........#',
      '#.....EE......EE....;;...#',
      '#............P...........#',
      '#.ooo..ooo...P...ooo..oo.#',
      '#............P...........#',
      '#.....PPPPPPPPPPP........#',
      '#.....P.........P....;;..#',
      '#..;;.P..oooo..PP........#',
      '#.....P..oooo...P........#',
      '#.....P.........P..EE....#',
      '#PPPPPP....EE...P..EE....#',
      '#......P...EE...P........#',
      '#..;;..P........PPPPPP...#',
      '#......PPPPPP.........P..#',
      '#.oooo......P....;;;;.P..#',
      '#.oooo......P........P...#',
      '#......;;...P...;;...P...#',
      '#...........P........P...#',
      '#..;;.......P........P..;#',
      '#...........P........P...#',
      '##########################',
    ],
    entities: [
      { x: 12, y: 20, type: 'story', emoji: '🚪', name: '大厦正门', id: 'door', main: true, story: 'ch8:start', req: 'ch7_done', done: 'ch8_done',
        altLines: ['「大门敞开着。前台摆了一块新牌子：『欢迎光临，本大厦已改为到点熄灯。』」'] },
      { x: 3, y: 16, type: 'heal', emoji: '☕', name: '99层茶水间', lines: '☕ 茶水间居然是暖色的。咖啡机还热着，墙上便利贴写着：「茶水间是本大厦唯一没有KPI的地方」。全队完全恢复！' },
      { x: 4, y: 19, type: 'save', emoji: '🕒', name: '一层打卡机', id: 's5' },
      { x: 22, y: 2, type: 'story', emoji: '🌀', name: '顶层的门', id: 'chouxiang', story: 'post:p_chouxiang', req: 'meme_all_done', done: 'p_chouxiang_done',
        altLines: ['「这扇门没有锁，但有股奇怪吸力。（梗图鉴收录齐全后，也许能推开它？）」'] },
      { x: 10, y: 8, type: 'npc', emoji: '🧍', name: '加班人偶', id: 'doll1', req: 'ch8_done', lines: ['「（人偶们放下了不存在的键盘，开始学着喝水、伸懒腰。）」'] },
      { x: 20, y: 14, type: 'npc', emoji: '🧍', name: '下班的人偶', id: 'doll2', req: 'ch8_done', lines: ['「（它背起不存在的包，朝门口走去。步子有点生疏，但很坚定。）」'] },
      { x: 2, y: 2, type: 'chest', emoji: '📦', id: 'cs1', item: 'i_dayao', n: 2, gold: 200 },
      { x: 23, y: 9, type: 'chest', emoji: '📦', id: 'cs2', item: 'i_v50', n: 1 },
      { x: 3, y: 14, type: 'chest', emoji: '📦', id: 'cs3', gold: 320 },
      { x: 24, y: 18, type: 'chest', emoji: '📦', id: 'cs4', item: 'i_catvideo', n: 2 },
    ],
  };

  /* ============ 霜语雪山（snow_mountain） ============ */
  M.snow_mountain = {
    name: '霜语雪山', pal: 'snow', bgm: 'forest', battleBg: 'snow',
    encounters: ['icecream_assassin', 'wolf_mist'],
    w: 26, h: 16, spawn: [12, 14], deco: '🌲',
    rows: [
      'MMMMMMMMMMMMPPMMMMMMMMMMMM',
      'MM^^^^^^^...PP...^^^^^^MMM',
      'MM^^^^......PP......^^^^MM',
      'MM^^....;;;.PP..;;....^^MM',
      'MM......;;;.PP..;;;....^MM',
      'MM..;;......PP....;;....MM',
      'MM..;;;.....PP..;;;;....MM',
      'MM...;;..TTTPPTTT;;.....MM',
      'MM.......TTTPPTTTT......MM',
      'MM..;;......PP.....;;...MM',
      'MM.....;;;..PP..;;......MM',
      'MM..;;;;....PP....;;....MM',
      'MM......TTTTPPTTT;;;....MM',
      'MM.........PPP..........MM',
      'MM........,PP,...........M',
      'MMMMMMMMMMMPPMMMMMMMMMMMMM',
    ],
    entities: [
      { x: 12, y: 15, type: 'exit', to: 'capital', toX: 25, toY: 1 },
      { x: 13, y: 1, type: 'story', emoji: '⛄', name: '山巅王座', id: 'xw', story: 'post:p_xuewang', req: 'post_unlocked', done: 'p_xuewang_done',
        altLines: ['「山巅的歌声还在，只是现在唱的是《恭喜发财》。」', '「雪王留了张纸条：『冷饮半价，随时来战。』」'] },
      { x: 4, y: 6, type: 'npc', emoji: '☃️', name: '小雪人', id: 'snow1', lines: ['「（它没有嘴，但你能感觉到它在笑。）」'] },
      { x: 21, y: 11, type: 'chest', emoji: '📦', id: 'sm1', item: 'i_ningmeng', n: 1, gold: 100 },
      { x: 3, y: 12, type: 'chest', emoji: '📦', id: 'sm2', item: 'i_fengyoujing', n: 2 },
      { x: 23, y: 3, type: 'chest', emoji: '📦', id: 'sm3', gold: 240 },
    ],
  };

  /* ============ 星期四平原（thursday） ============ */
  M.thursday = {
    name: '星期四平原', pal: 'grass', bgm: 'field', battleBg: 'farm',
    encounters: ['boar_mini', 'monkey_malou'],
    w: 24, h: 14, spawn: [2, 7], deco: '🌲',
    rows: [
      'TTTTTTTTTTTTPPTTTTTTTTTT',
      'T..,,......,P,.....,,..TT',
      'T..;;;;......P....;;;..TT',
      'T..;;;;..,...P...,;;;..TT',
      'T....;;..,...PP....;...TT',
      'T..,....;;;;.P.........TT',
      'T..,,,..;;;;.P....,,,..TT',
      'T..,,,......PP....,,,..TT',
      'T......;;;..P....,....TTT',
      'T..;;..;;;..P.........,TT',
      'T..;;.......P....;;;.,.TT',
      'T.....,.....P...;;;;...TT',
      'T...........P..........TT',
      'TTTTTTTTTTTTPPTTTTTTTTTTT',
    ],
    entities: [
      { x: 12, y: 13, type: 'exit', to: 'farm', toX: 16, toY: 1 },
      { x: 12, y: 1, type: 'story', emoji: '🐓', name: '金冠战斗鸡', id: 'kfc', story: 'post:p_kfc', req: 'post_unlocked', done: 'p_kfc_done',
        altLines: ['「平原中央立着一根巨大的炸鸡形状纪念碑，刻着：『星期四永存』。」'] },
      { x: 20, y: 8, type: 'monster', emoji: '🦙', name: '神兽·驼驼', id: 'tt3', enemies: ['alpaca_tuotuo'],
        lines: '（金色的草丛里，驼驼正在打滚。它看到你们，做了个鬼脸，摆好了架势！）' },
      { x: 4, y: 4, type: 'chest', emoji: '📦', id: 'th1', item: 'i_v50', n: 1 },
      { x: 21, y: 2, type: 'chest', emoji: '📦', id: 'th2', gold: 200 },
    ],
  };

  /* ============ 轮回公路（road_truck） ============ */
  M.road_truck = {
    name: '轮回公路', pal: 'memory', bgm: 'field', battleBg: 'field',
    w: 22, h: 12, spawn: [19, 6], deco: '🌲',
    rows: [
      'TTTTTTTTTTTTTTTTTTTTTT',
      'T....................T',
      'T..;;....;;;;....;;..T',
      'T....................T',
      'TPPPPPPPPPPPPPPPPPPPPT',
      'TPPPPPPPPPPPPPPPPPPPPT',
      'T....................T',
      'T...;;.......;;;.....T',
      'T....................T',
      'T..W..........W......T',
      'T..WW.........WW.....T',
      'TTTTTTTTTTTTTTTTTTTTTT',
    ],
    entities: [
      { x: 20, y: 6, type: 'exit', to: 'canal', toX: 12, toY: 7 },
      { x: 10, y: 4, type: 'story', emoji: '🚚', name: '熄火的卡车', id: 'truck', story: 'post:p_truck', req: 'post_unlocked', done: 'p_truck_done',
        altLines: ['「路边停着一辆擦得锃亮的卡车，车牌写着：『先看灯，再过马路』。」'] },
      { x: 4, y: 1, type: 'chest', emoji: '📦', id: 'rt1', item: 'i_naicha', n: 1 },
      { x: 17, y: 9, type: 'chest', emoji: '📦', id: 'rt2', gold: 150, item: 'i_bandaid', n: 3 },
    ],
  };
})();
